In [1]:
import pandas as pd
import os
import duckdb

In [2]:
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/workspaces/spotify_insights/airflow/credentials/google_credentials.json'
#source_path = "gs://spotify-insights-pipeline-data/raw-tables"
streams_source_path = "gs://spotify-insights-pipeline-data/stg_spotify_streams/dtype_dedup"

In [3]:
stg_spotify_streams = pd.read_parquet(streams_source_path, engine="pyarrow")
stg_spotify_streams = stg_spotify_streams[stg_spotify_streams['username'] == 'joseph.higaki']
stg_spotify_streams

,stream_id,streamed_at,platform,ms_played,conn_country,ip_addr,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,...,spotify_episode_uri,reason_start,reason_end,shuffle,skipped,offline,incognito_mode,offline_timestamp,username,streamed_year
58061,3a485a35bc0e69b13dd346231d6e0d4f,2014-12-23 00:37:58+00:00,"Android OS 4.4.4 API 19 (motorola, XT1097)",300826,US,66.165.162.68,Smells Like Teen Spirit,Nirvana,Nirvana,spotify:track:4hy4fb5D1KL50b3sng9cjw,...,None,appload,trackdone,True,True,True,True,NaN,joseph.higaki,2014
58062,182d23a8a69eedb73e7c3a44a2bab6d5,2014-12-23 00:40:47+00:00,"Android OS 4.4.4 API 19 (motorola, XT1097)",169133,US,66.165.162.68,Rape Me,Nirvana,Nirvana,spotify:track:47KVHb6cOVBZbmXQweE5p7,...,None,trackdone,trackdone,True,True,True,True,NaN,joseph.higaki,2014
58063,cccab707a4b2d4d2f29f6688d8cc281a,2014-12-23 00:46:44+00:00,"Android OS 4.4.4 API 19 (motorola, XT1097)",356080,US,66.165.162.68,Sweet Child O' Mine,Guns N' Roses,Appetite For Destruction,spotify:track:7o2CTH4ctstm8TNelqjb51,...,None,trackdone,trackdone,True,True,True,True,NaN,joseph.higaki,2014
58064,98f0e6fbf3499b3c74bee057a80619b4,2014-12-23 00:49:35+00:00,"Android OS 4.4.4 API 19 (motorola, XT1097)",170800,US,66.165.162.68,Rock And Roll All Nite,KISS,Greatest Kiss,spotify:track:3qei6Em6zqxjFuPfhhghWM,...,None,trackdone,trackdone,True,True,True,True,NaN,joseph.higaki,2014
58065,1a8efb967a73de58831d3a28b8c75b7f,2014-12-23 00:54:26+00:00,"Android OS 4.4.4 API 19 (motorola, XT1097)",290280,US,66.165.162.68,Message In A Bottle - Remastered 2003,The Police,Reggatta De Blanc,spotify:track:2inge47GpvkHhe0VCXP8Zd,...,None,trackdone,trackdone,True,True,True,True,NaN,joseph.higaki,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152728,4f67f885b94cd9fde7d741614509ccb5,2024-12-04 06:55:39+00:00,android,282653,ES,79.153.169.248,Voodoo,Godsmack,Godsmack,spotify:track:5uGsG0LfotfWDq6hql4h53,...,None,trackdone,trackdone,True,True,True,True,1.733295e+09,joseph.higaki,2024
152729,2d77649d593863f0944b8cbb3370cd12,2024-12-04 06:58:59+00:00,android,199906,ES,79.153.169.248,Last Resort,Papa Roach,Infest,spotify:track:5W8YXBz9MTIDyrpYaCg2Ky,...,None,trackdone,trackdone,True,True,True,True,1.733295e+09,joseph.higaki,2024
152730,3d09fac078d3518bb28d431729652109,2024-12-04 07:04:05+00:00,android,304840,ES,79.153.169.248,Uprising,Muse,The Resistance,spotify:track:4VqPOruhp5EdPBeR92t6lQ,...,None,trackdone,trackdone,True,True,True,True,1.733296e+09,joseph.higaki,2024
152731,1f6cf1e59bf4e9c4c984cbc5e29240c2,2024-12-04 07:26:58+00:00,android,148181,ES,79.117.89.98,Killing In The Name,Rage Against The Machine,Rage Against The Machine - XX (20th Anniversar...,spotify:track:59WN2psjkt1tyaxjspN8fp,...,None,trackdone,unknown,True,True,True,True,1.733296e+09,joseph.higaki,2024
152732,192cae431b05cc5cee820b1abed36e31,2024-12-05 15:25:10+00:00,android,408,AD,85.94.179.153,Killing In The Name,Rage Against The Machine,Rage Against The Machine - XX (20th Anniversar...,spotify:track:59WN2psjkt1tyaxjspN8fp,...,None,appload,logout,True,True,True,True,1.733411e+09,joseph.higaki,2024

## Load user location and location

In [ ]:
airport_location_path = "/workspaces/spotify_insights/0_tmp_data/airport_code_location/airports-code@public.csv"
user_location_path = "/workspaces/spotify_insights/0_tmp_data/user_location/user_location.csv"

In [53]:


airport_location = pd.read_csv(airport_location_path, delimiter=";")
airport_location

,Airport Code,Airport Name,City Name,Country Name,Country Code,Latitude,Longitude,World Area Code,City Name geo_name_id,Country Name geo_name_id,coordinates
0,CRS,Corsicana,Corsicana,United States,US,32.100000,-96.466667,67,4683462,6252001.0,"32.1, -96.466667"
1,ACP,Sahand,Sahand,Iran,IR,37.733333,46.450000,632,\N,130758.0,"37.733333, 46.45"
2,TBE,Timbunke,Timbunke,Papua New Guinea,PG,-4.183333,143.516667,804,\N,2088628.0,"-4.183333, 143.516667"
3,LWO,Snilow,Lviv,Ukraine,UA,49.812500,23.956111,488,702550,690791.0,"49.8125, 23.956111"
4,SCP,St Crepin,St Crepin,France,FR,44.683333,6.583333,427,\N,3017382.0,"44.683333, 6.583333"
...,...,...,...,...,...,...,...,...,...,...,...
9182,SJD,Los Cabos,San Jose Del Cabo,Mexico,MX,23.151944,-109.721111,148,\N,3996063.0,"23.151944, -109.721111"
9183,HVS,Municipal,Hartsville,United States,US,34.400000,-80.116667,67,4628109,6252001.0,"34.4, -80.116667"
9184,GDG,Magdagachi,Magdagachi,Russian Federation,RU,53.466667,125.800000,770,2020591,2017370.0,"53.466667, 125.8"
9185,CHO,Albemarle,Charlottesville,United States,US,38.133333,-78.450000,67,4752031,6252001.0,"38.133333, -78.45"
9186,CMW,Ign Agramonte Intl,Camaguey,Cuba,CU,21.416667,-77.866667,219,3566067,3562981.0,"21.416667, -77.866667"

In [54]:
user_location = pd.read_csv(user_location_path)
user_location['start_at'] = user_location['start_at'].astype("datetime64[ns, UTC]") 
user_location['end_at'] = user_location['end_at'].astype("datetime64[ns, UTC]") 
user_location.dtypes

username                     object
start_at        datetime64[ns, UTC]
end_at          datetime64[ns, UTC]
airport_code                 object
dtype: object

In [55]:
con =  duckdb.connect()
con.register('airport_location', airport_location)
con.register('user_location', user_location)
con.register('stg_spotify_streams', stg_spotify_streams)

In [59]:
query = """
        
            select             
            *
            from user_location 
        
    """        
df = con.execute(query).fetchdf()
df.dtypes

username                         object
start_at        datetime64[us, Etc/UTC]
end_at          datetime64[us, Etc/UTC]
airport_code                     object
dtype: object

In [60]:
df

,username,start_at,end_at,airport_code
0,joseph.higaki,2014-01-01 00:00:00+00:00,2020-10-17 04:59:59+00:00,LIM
1,joseph.higaki,2020-10-17 05:00:00+00:00,2024-09-10 04:59:59+00:00,BCN
2,joseph.higaki,2024-06-20 18:35:00+00:00,2024-06-24 09:59:59+00:00,CDG
3,joseph.higaki,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR
4,joseph.higaki,2020-06-25 00:16:00+00:00,2024-09-10 04:59:59+00:00,BCN
5,joseph.higaki,2024-09-10 05:00:00+00:00,2024-09-17 04:59:59+00:00,BIQ
6,joseph.higaki,2024-09-17 05:00:00+00:00,2024-12-19 04:59:59+00:00,BCN

In [57]:
#where = " and ('2024-09-09 00:00:00+00:00' < streamed_at  and streamed_at <  '2024-09-18 00:00:00+00:00') "
where = " and airport_code = 'LHR' "
#where = " and conn_country = 'PT' "


query = f"""
        with join_user_location as (
            select             
            *
            from stg_spotify_streams 
            left join user_location on
                stg_spotify_streams.streamed_at between user_location.start_at and user_location.end_at
        )
        select 
            streamed_at,
            ms_played,
            ip_addr,
            conn_country,
            start_at,
            end_at,
            airport_code,
            master_metadata_track_name,
            master_metadata_album_artist_name
            
        from join_user_location 
        where 1=1
            {where}            
        order by streamed_at, stream_id
    """        

df = con.execute(query).fetchdf()
display(df)

,streamed_at,ms_played,ip_addr,conn_country,start_at,end_at,airport_code,master_metadata_track_name,master_metadata_album_artist_name
0,2020-06-24 10:16:36+00:00,240295,190.113.208.121,PE,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,Heart-Shaped Box,Nirvana
1,2020-06-24 10:17:31+00:00,40866,190.113.208.121,PE,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,Heart-Shaped Box,Nirvana
2,2020-06-24 10:19:46+00:00,134200,190.113.208.121,PE,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,Lump,The Presidents Of The United States Of America
3,2020-06-24 10:23:00+00:00,193653,190.113.208.121,PE,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,Lonely Boy,The Black Keys
4,2020-06-24 10:28:33+00:00,332626,190.113.208.121,PE,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,Creep,Stone Temple Pilots
...,...,...,...,...,...,...,...,...,...
45121,2024-06-24 20:32:06+00:00,1529782,79.116.113.106,ES,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,None,None
45122,2024-06-24 20:32:17+00:00,9284,79.116.113.106,ES,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,None,None
45123,2024-06-24 20:52:34+00:00,1215271,79.116.113.106,ES,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,None,None
45124,2024-06-24 21:57:05+00:00,3149385,79.116.113.106,ES,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,None,None
45125,2024-06-24 23:26:31+00:00,2813720,79.117.102.183,ES,2020-06-24 10:00:00+00:00,2024-06-25 00:15:59+00:00,LHR,None,None